// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVbMM1TBgyasKBp6Wf5vDhS627bU6toD4',
    appId: '1:434986329048:web:6ca2430970cefaeab288ad',
    messagingSenderId: '434986329048',
    projectId: 'todolist-a81b3',
    authDomain: 'todolist-a81b3.firebaseapp.com',
    storageBucket: 'todolist-a81b3.appspot.com',
    measurementId: 'G-DYLKQYNGCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMjQKs61D8VjQ7DjISNa1VCbffw_xjsRE',
    appId: '1:434986329048:android:16ea2caf2ecb11a7b288ad',
    messagingSenderId: '434986329048',
    projectId: 'todolist-a81b3',
    storageBucket: 'todolist-a81b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9hc7hwhIKyonEbOpIgRowBtyIzUgRVPY',
    appId: '1:434986329048:ios:e474d6cc4c2d3323b288ad',
    messagingSenderId: '434986329048',
    projectId: 'todolist-a81b3',
    storageBucket: 'todolist-a81b3.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9hc7hwhIKyonEbOpIgRowBtyIzUgRVPY',
    appId: '1:434986329048:ios:0f2fd253cbe9a94db288ad',
    messagingSenderId: '434986329048',
    projectId: 'todolist-a81b3',
    storageBucket: 'todolist-a81b3.appspot.com',
    iosBundleId: 'com.example.toDoList.RunnerTests',
  );
}
